language: rust
rust:
- stable
- beta
- nightly

script:
- cargo test

matrix:
  include:
  - name: cargo fmt
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

  - name: cargo +nightly bench
    rust: nightly
    script:
    - cargo bench
