[package]
name = "route-recognizer"
description = "Recognizes URL patterns with support for dynamic and glob segments"
license = "MIT"
repository = "https://github.com/conduit-rust/route-recognizer.rs"
keywords = ["router", "url"]
edition = "2018"

version = "0.1.13"
authors = ["wycats"]
